Q and A - 16-12-59/MvcMovie_Completed2 final/MvcMovie/Controllers/qaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcMovie.Models;

namespace MvcMovie.Controllers
{

    public class qaController : Controller
    {
        private MovieDBContext db = new MovieDBContext();

        // GET: Movies/index/war
        public ActionResult Index(string movieGenre, string searchString)
        {

            var GenreLst = new List<string>();
            var GenreQry = from d in db.Movies
                           orderby d.Genre
                           select d.Genre;

            GenreLst.AddRange(GenreQry.Distinct());
            ViewBag.movieGenre = new SelectList(GenreLst);

            //LINQ
            var movies = from m in db.Movies select m;
            if (!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(
                    s => s.Title.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(movieGenre))
            {
                movies = movies.Where(x => x.Genre == movieGenre);
            }

            return View(movies);
        }

        [HttpPost]
        public string Index(FormCollection fc, string searchString)
        {
            return "<h3> From [HttpPost]Index: " + searchString + "</h3>";
        }

        // GET: Movies/Details/5

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // GET: Movies/Create
        public ActionResult Create()
        {
            var GenreLst = new List<string>();
            var GenreQry = from d in db.Movies
                           orderby d.Genre
                           select d.Genre;

            GenreLst.AddRange(GenreQry.Distinct());
            ViewBag.movieGenre = new SelectList(GenreLst);

            return View();

        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,Genre,Status,Rating")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Movies.Add(movie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(movie);
        }
        

        // GET: Movies/Edit/5
        public ActionResult Edit(int? id)
        {
            var GenreLst = new List<string>();
            var GenreQry = from d in db.Movies
                           orderby d.Genre
                           select d.Genre;

            GenreLst.AddRange(GenreQry.Distinct());
            ViewBag.movieGenre = new SelectList(GenreLst);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,Genre,Status,Rating")] Movie movie)
        {
            var GenreLst = new List<string>();
            var GenreQry = from d in db.Movies
                           orderby d.Genre
                           select d.Genre;

            GenreLst.AddRange(GenreQry.Distinct());
            ViewBag.movieGenre = new SelectList(GenreLst);

            if (ModelState.IsValid)
            {
                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("admin");
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.Movies.Find(id);
            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult admin(string movieStatus, string movieGenre, string searchString)
        {
            if(Session["adminlogin"] == null)
            {
                return RedirectToAction("adminLogin");
            }

            ViewBag.test = Session["adminlogin"];

            //genre
            var GenreLst = new List<string>();
                var GenreQry = from d in db.Movies
                               orderby d.Genre
                               select d.Genre;

                GenreLst.AddRange(GenreQry.Distinct());
                ViewBag.movieGenre = new SelectList(GenreLst);

            //status
            var GenreLst2 = new List<string>();
            var GenreQry2 = from d in db.Movies
                           orderby d.Status
                           select d.Status;
            GenreLst2.AddRange(GenreQry2.Distinct());
            ViewBag.movieStatus = new SelectList(GenreLst2);

            //LINQ
            var movies = from m in db.Movies select m;

            if (!String.IsNullOrEmpty(movieStatus))
            {
                movies = movies.Where(st => st.Status.Contains(movieStatus));
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.Title.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(movieGenre))
            {
                movies = movies.Where(x => x.Genre == movieGenre);
            }

            return View(movies);

        }

        //login admin
        public ActionResult adminLogin(string userId, string password)
        {
            
            if (Session["adminlogin"] != null)//login state
            {
                return RedirectToAction("admin");
            }
            if (userId == "admin2" && password == "admin2")//login
            {                
                Session["adminlogin"] = "login";   
                return RedirectToAction("admin");
            }            
            Session["adminlogin"] = null;
            return View();
        }

        public ActionResult logoutsession()
        {            
            Session["adminlogin"] = null;
            return RedirectToAction("admin");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Q and A - 16-12-59/MvcMovie_Completed2 final/MvcMovie/Views/qa/Create.cshtml
@model MvcMovie.Models.Movie

@{
    ViewBag.Title = "Ask New Question";
}

<h2>Ask New Question</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownList("Genre", (SelectList)ViewBag.movieGenre, "All", new { @class = "form-control col-sm-1" })
                   @*@Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                   @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })*@

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" , @Value = "ยังไม่ได้รับคำตอบ" , @readonly = "readonly"} })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ask Question" class="btn btn-default" />
                <!-- Write SQL insert command to database-->
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Q and A - 16-12-59/MvcMovie_Completed2 final/MvcMovie/Views/qa/Delete.cshtml
@model MvcMovie.Models.Movie

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @*Html.DisplayFor(model => model.Rating)*@
            @Html.TextAreaFor(model => model.Rating, new { @class = "form-control", @rows = 10, @readonly = true })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Q and A - 16-12-59/MvcMovie_Completed2 final/MvcMovie/Views/qa/Details.cshtml
@model MvcMovie.Models.Movie

@{
    ViewBag.Title = "Details";
}

<h2>รายละเอียดปัญหา</h2>

<div width="50">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd>
            <table>
                <tr>
                    <td width="350">@*Html.DisplayFor(model => model.Rating)*@
                    @Html.TextAreaFor(model => model.Rating, new { @class = "form-control", @rows = 10 , @readonly = true })
                    </td>
                </tr>
            </table>
        </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Status)
            </dd>
</dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Q and A - 16-12-59/MvcMovie_Completed2 final/MvcMovie/Views/qa/Edit.cshtml
@model MvcMovie.Models.Movie

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
    
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Genre", (SelectList)ViewBag.movieGenre, "--Select--", new { @class = "form-control col-sm-1" })
                @*@Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @*@Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.TextAreaFor(model => model.Rating, new { @class="form-control", @rows = 10 })
                @*@Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    List<SelectListItem> listItems = new List<SelectListItem>();


                    listItems.Add(new SelectListItem
                    {
                        Text = "ตอบแล้ว",
                        Value = "ตอบแล้ว"
                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "ยังไม่ได้รับคำตอบ",
                        Value = "ยังไม่ได้รับคำตอบ",
                        Selected = true
                    });
                }

                @Html.DropDownListFor(model => model.Status, listItems, new { @class = "form-control" } )
                @*Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" onclick="admin" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Q and A - 16-12-59/MvcMovie_Completed2 final/MvcMovie/Views/qa/Index.cshtml
@model IEnumerable<MvcMovie.Models.Movie>

@{
    ViewBag.Title = "Index";
}
    <div><center><h1 class="control-label">Q&A Freshy</h1></center></div><br><br>

    <p>
        <button type="button" class="btn btn-default">@Html.ActionLink("Ask New Question", "Create")</button>

        @using (Html.BeginForm("Index", "qa", FormMethod.Get))
        {
            @*<p>
                      หมวดหมู่: @Html.DropDownList("movieGenre", "All")
                      ปัญหา: @Html.TextBox("SearchString")

                <input type="submit" value="Filter" />
                  </p>*@
            @Html.Label("หมวดหมู่:", htmlAttributes: new { @class = "control-label col-sm-1" })
            @*@Html.DropDownList("movieGenre", "All")*@
            @Html.DropDownList("movieGenre", (SelectList)ViewBag.movieGenre, "All", new { @class = "form-control col-sm-1" })
            @Html.Label("ปัญหา:", htmlAttributes: new { @class = "control-label col-sm-1" })
            @Html.Editor("SearchString", new { htmlAttributes = new { @class = "form-control col-sm-1", placeholder = "Ex: ร้านข้าวใกล้มอ.", @type = "text" } })
            <input type="submit" value="Filter" class="btn btn-default" />
        }

    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    <button type="button" class="btn btn-default">@Html.ActionLink("Details", "Details", new { id = item.ID })</button>
                </td>
            </tr>
        }

    </table>

Q and A - 16-12-59/MvcMovie_Completed2 final/MvcMovie/Views/qa/admin.cshtml
@model IEnumerable<MvcMovie.Models.Movie>

@{
    ViewBag.Title = "admin";
}
<div><center><h1 class="control-label">Administrator<span class="glyphicon glyphicon-user"></span></h1></center></div><br>

<div class="col-md-10">
    <button type="button" class="btn btn-default">@Html.ActionLink("Ask New Question", "Create")</button>
</div>
<div class="col-md-1">
    <button type="button" class="btn btn-danger">@Html.ActionLink("Logout", "logoutsession")</button>
</div><br><br>
<p>


    @using (Html.BeginForm("admin", "qa", FormMethod.Get))
    {

        
        @Html.Label("หมวดหมู่:", htmlAttributes: new { @class = "control-label col-sm-1" })
        @Html.DropDownList("movieGenre", (SelectList)ViewBag.movieGenre, "All", new { @class = "form-control col-sm-1" })
        <br><br><div>
            @Html.Label("สถานะ:", htmlAttributes: new { @class = "control-label col-sm-1" })
            @Html.DropDownList("movieStatus", (SelectList)ViewBag.movieStatus, "All", new { @class = "form-control col-sm-1" })

            @Html.Label("ปัญหา:", htmlAttributes: new { @class = "control-label col-sm-1" })
            @Html.Editor("SearchString", new { htmlAttributes = new { @class = "form-control col-sm-1", placeholder = "Ex: ร้านข้าวใกล้มอ.", @type = "text" } })
            <input type="submit" value="Filter" class="btn btn-default" />
        </div><br><br>
    }
</p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @if (item.Status == "ยังไม่ได้รับคำตอบ")
                    {
                        <font color="red">@Html.DisplayFor(modelItem => item.Status)</font>
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.Status)
                    }

                </td>
                <td>
                    <button type="button" class="btn btn-default">
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID })
                    </button>
                        <button type="button" class="btn btn-default">
                            @Html.ActionLink("Details", "Details", new { id = item.ID })
                        </button>
                            <button type="button" class="btn btn-default">@Html.ActionLink("Delete", "Delete", new { id = item.ID })</button>
</td>
            </tr>
        }

    </table>

Q and A - 16-12-59/MvcMovie_Completed2 final/MvcMovie/Views/qa/adminLogin.cshtml
@{
    ViewBag.Title = "adminLogin";
}

<center>

                @using (Html.BeginForm("adminLogin", "qa", FormMethod.Post))
            {
                    <br/>
                    <br />
                    <br />
                               @Html.Label("Admin Login", htmlAttributes: new { @class = "control-label" })
                    <br />
                    <br />
                               @*Html.Label("User ID", htmlAttributes: new { @class = "control-label" })*@
                               @Html.Editor("userId", new { htmlAttributes = new { @class = "form-control", placeholder = "User ID" } })
                               <br />
                               @*Html.Label("Password", htmlAttributes: new { @class = "control-label" })*@
                               @Html.Editor("password", new { htmlAttributes = new { @class = "form-control", placeholder = "Password", @type = "password" } })
                       <br/>
                                <input type="submit" value="Login" class="btn btn-default" />
                                <br/>
                                <br />
                }
    </center>